In [ ]:
import numpy as np

In [ ]:
a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
a=[1,2,3,4,5]
type(a)

list

In [ ]:
[i**2 for i in a]

[1, 4, 9, 16, 25]

In [ ]:
b=np.array(a)
type(b)

numpy.ndarray

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
b**2

array([ 1,  4,  9, 16, 25])

In [ ]:
print(b**2)

[ 1  4  9 16 25]


In [ ]:
a=[1,2,3,4,'champu']
type(a)

list

In [ ]:
[i**2 for i in a]

[1, 4, 9, 16, 25]

In [ ]:
a=[1,2,3,4,5]

In [ ]:
l=range(1000000)
%timeit [i**2 for i in l]

1.25 s ± 424 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
l=np.array(range(1000000))
%timeit [i**2 for i in l]

170 ms ± 35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
arr=np.array(range(1000000))
arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
arr.ndin

1

In [ ]:
arr.shape

(1000000,)

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(arr.ndim, arr.shape)

1 (8,)


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])


In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(4, 3)

In [ ]:
arr=np.array([[1,[2],3],[4,[5],6],[7,[8],9]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

In [ ]:
arr=np.array([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]],[[10],[11],[12]]])


In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(4, 3, 1)

In [ ]:
arr=np.array([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9],[15]],[[10],[11],[12]]])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
a=np.array(range(5))
a

array([0, 1, 2, 3, 4])

In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.array(range(1,5))

array([1, 2, 3, 4])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
ls=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
ls[-1:5]

[]

In [ ]:
ls[-5:-2]

[6, 7, 8]

In [ ]:
ls[-4:-7:-1]

[7, 6, 5]

In [ ]:
a=1+1.0
a

2.0

In [ ]:
a=2.0
a=int(a)
print(a)

2


In [ ]:
a=int(input())

In [ ]:
arr=np.arange(5)
print(arr)
arr[2:4]=0
print(arr[2:4])

[0 1 2 3 4]
[0 0]


In [ ]:
arr

array([0, 1, 0, 0, 4])

In [ ]:
np.array(['sunny',1,1.0,True])

array(['sunny', '1', '1.0', 'True'], dtype='<U32')

In [ ]:
ls=[1,2,3,4,5,6,7,8]

In [ ]:
ls[1:4]   #lower to higher

[2, 3, 4]

In [ ]:
ls[4:1:-1]

[5, 4, 3]

In [ ]:
ls[3:-1]

[4, 5, 6, 7]

In [ ]:
ls[-1:4]

In [ ]:
ls[-1:3:-1]

[8, 7, 6, 5]

In [ ]:
import numpy as np

In [ ]:
m1=np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
print(m1[3:9])

[3 4 5 6 7 8]


In [ ]:
m1[-1:5]

array([], dtype=int64)

In [ ]:
print(m1[-1:5])

[]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

[1 2 6 7 8]


In [ ]:
a=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
a[a<6]

TypeError: '<' not supported between instances of 'list' and 'int'

In [ ]:
[i<6 for i in a]

[True, True, True, True, True, False, False, False, False, False]

In [ ]:
m1=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
m1[m1<6]

array([1, 2, 3, 4, 5])

In [ ]:
m1=np.array([1,2,3,4,5,6,7,8,9,10])
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1[m1<6]

array([1, 2, 3, 4, 5])

In [ ]:
m1[m1%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
m1=np.array([1,2,3,4,5,6,7,8,9,10])
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1=np.array([1,2,3,4,5,6,7,8,9,10])
m1<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
m1[[1, 2, 5]]

array([2, 3, 6])

In [ ]:
m1[[ True,  True,  True,  True,  True, False, False, False, False,
       False]]

array([1, 2, 3, 4, 5])

In [ ]:
m1[m1<6]

array([1, 2, 3, 4, 5])

In [ ]:
m1[[ True,  True,  True,  True,  True, False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 6

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
(arr, dtype='float64')

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (<ipython-input-43-a4ab0031b06f>, line 1)

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50], dtype='float64')
arr


array([10., 20., 30., 40., 50.])

In [ ]:
url = 'https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view?usp=sharing'

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 9.64MB/s]


In [ ]:
score=np.loadtxt('survey.txt',dtype='int')

In [ ]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [ ]:
detractors=score[score<=6]
len_detractors=len(detractors)

In [ ]:
promoters=score[score>=9]
len_promoters=len(promoters)

In [ ]:
total=len(score)
print(total)

1167


In [ ]:
NPS=((len_promoters*100)/total)-((len_detractors*100)/total)
NPS

23.73607540702656

In [ ]:
np.round(NPS,2)

23.74

In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])

In [ ]:
-5 9 -3 5 10   *-1
5 -9 3 -5 -10